-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE drivers CASCADE CONSTRAINTS;

DROP TABLE drivers_races CASCADE CONSTRAINTS;

DROP TABLE races CASCADE CONSTRAINTS;

DROP TABLE racetype CASCADE CONSTRAINTS;

DROP TABLE season CASCADE CONSTRAINTS;

DROP TABLE teams CASCADE CONSTRAINTS;

CREATE TABLE drivers (
    driverid       NUMBER(7) NOT NULL,
    drivername     VARCHAR2(25) NOT NULL,
    country        VARCHAR2(30) NOT NULL,
    dateofbirth    DATE NOT NULL,
    driverpoints   NUMBER(3) NOT NULL,
    teams_teamid   NUMBER(7) NOT NULL
);

ALTER TABLE drivers ADD CONSTRAINT drivers_pk PRIMARY KEY ( driverid );

CREATE TABLE drivers_races (
    drivers_driverid   NUMBER(7) NOT NULL,
    races_raceid       NUMBER(7) NOT NULL
);

ALTER TABLE drivers_races ADD CONSTRAINT drivers_races_pk PRIMARY KEY ( drivers_driverid,
                                                                        races_raceid );

CREATE TABLE races (
    raceid                NUMBER(7) NOT NULL,
    grandprix             VARCHAR2(30) NOT NULL,
    "Date"                DATE NOT NULL,
    laps                  NUMBER(2) NOT NULL,
    time                  NUMBER(3, 2) NOT NULL,
    winner                VARCHAR2(25),
    season_year           NUMBER(4) NOT NULL,
    racetype_racetypeid   NUMBER(7) NOT NULL
);

ALTER TABLE races ADD CONSTRAINT races_pk PRIMARY KEY ( raceid );

CREATE TABLE racetype (
    racetypeid   NUMBER(7) NOT NULL,
    racetype     VARCHAR2(20) NOT NULL
);

ALTER TABLE racetype ADD CONSTRAINT racetype_pk PRIMARY KEY ( racetypeid );

CREATE TABLE season (
    year NUMBER(4) NOT NULL
);

ALTER TABLE season ADD CONSTRAINT season_pk PRIMARY KEY ( year );

CREATE TABLE teams (
    teamid           NUMBER(7) NOT NULL,
    teamname         VARCHAR2(50) NOT NULL,
    base             VARCHAR2(50) NOT NULL,
    teamchief        VARCHAR2(25) NOT NULL,
    techincalchief   VARCHAR2(25) NOT NULL,
    firstteamentry   NUMBER(4) NOT NULL,
    teampoints       NUMBER(3) NOT NULL
);

ALTER TABLE teams ADD CONSTRAINT teams_pk PRIMARY KEY ( teamid );

ALTER TABLE drivers_races
    ADD CONSTRAINT drivers_races_drivers_fk FOREIGN KEY ( drivers_driverid )
        REFERENCES drivers ( driverid );

ALTER TABLE drivers_races
    ADD CONSTRAINT drivers_races_races_fk FOREIGN KEY ( races_raceid )
        REFERENCES races ( raceid );

ALTER TABLE drivers
    ADD CONSTRAINT drivers_teams_fk FOREIGN KEY ( teams_teamid )
        REFERENCES teams ( teamid );

ALTER TABLE races
    ADD CONSTRAINT races_racetype_fk FOREIGN KEY ( racetype_racetypeid )
        REFERENCES racetype ( racetypeid );

ALTER TABLE races
    ADD CONSTRAINT races_season_fk FOREIGN KEY ( season_year )
        REFERENCES season ( year );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
